- .github/workflows/build_gdextension.yml
- .github/workflows/ci.yml
- scripts/build-sentry-native.sh
This PR adds CI and a workflow to build and package GDExtension libraries in a ready-to-test form. CI is executed on push and PR.
GHA files:
- **ci.yml**: CI workflow.
- **build_gdextension.yml**: Build workflow.
Notes:
- I will add testing in a separate PR after both this and #19 are merged.
- Waiting for #25 and #26 before proceeding with this one.
Resolves #16
> Implement GHA workflow to build the Godot SDK

- src/sentry/contexts.cpp
- src/sentry/contexts.h
- src/sentry/native/native_sdk.cpp
The current default is to set context values during initialization, which works for most cases. The only context that is currently updated is "godot_performance".
This PR introduces a code path that updates values in the standard `Device` context just before the event is sent.
Values that are dynamically updated in the Device context with this PR: `orientation`, `free_memory`, `usable_memory`, `free_storage`.
> Update dynamic values in the Device context

- .gitignore
- .gitmodules
- SConstruct
This PR adds [godot-cpp](https://github.com/godotengine/godot-cpp) as a submodule, instead of a build-time checkout.
> Add `godot-cpp` as a submodule

- .gitattributes
Normalize line ending to `LF`. Ensure consistent line endings across different OS.
> chore: Normalize line endings

- project/test/test_sentry_user.gd
Fix user test failing due to user ID no longer assigned if `send-default-pii` is enabled
> Fix user test failing

- src/register_types.cpp
- src/sentry_sdk.cpp
This PR fixes a crash on Windows related to memory release, adds sanity checks and debug prints.
> Fix crash on shutdown on Windows

- src/sentry_options.cpp
- src/sentry_options.h
- src/sentry_sdk.cpp
This PR introduces a new option `disabled_in_editor` which defaults to `true`. Disabled SDK does not process events or errors, and doesn't connect to Sentry servers. The extension library is still loaded for the purpose of editing options and such.
This option does NOT disable SDK while running projects from the editor. Unit tests also run fine, since they are executed in a separate process (not inside editor).
> Option to disable SDK in the editor

- project/main.gd
- src/sentry/native/native_sdk.cpp
This PR fixes sentry level not properly set in `SentrySDK.capture_message()`
> Fix sentry level in `capture_message`

- .github/workflows/build_gdextension.yml
- .github/workflows/ci.yml
- .github/workflows/unit_tests.yml
Run unit tests in CI using Windows and Linux runners. This will help us detect compilation and runtime issues early on.
> GHA: Run unit tests in CI

- src/sentry_logger.cpp
- src/sentry_logger.h
- src/sentry_options.cpp
- src/sentry_options.h
- **Problems**
- Repeatedly logging the same error in a loop
- Errors recurring every frame
- Multiple various errors overwhelming quotas
- Specific error type spamming & overwhelming quotas (?)
- **Goals**
- Protect the frame budget
- Reduce impact on quotas
- Increase coverage: avoid duplicates, and some errors not reported at all
- **Complex solution**
- **Limit errors to N events reported per frame**
- Rationale: Protect the frame budget.
- Options: `limits/events_per_frame`, ~~`limits/breadcrumbs_per_frame`~~
- **Limit errors to 1 error captured per (file, lineno) within a T interval.**
- Rationale: Increase error coverage and reduce redundancy.
- Options: `limits/repeated_error_window_ms`
- **Limit to N events ~~& M breadcrumbs~~ reported within a T milliseconds interval**
- …
> Feature: Logger limits and throttling

- .craft.yml
- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- scripts/bump-version.ps1
Included:
- Bump version script
- Craft configuration
- Package workflow
- Release workflow
Closes #30
> Feature: Automate release flow

- .github/workflows/ci.yml
Remove `sentry-godot-gdextension` artifact as the last step in CI, because it lacks executable permissions on `crashpad_handler`. These permissions are corrected in the "package" job which produces a separate artifact, so this encourages downloading the correct zip archive.
For more details, see #41
Resolves #41
> ci: Delete intermediary artifact to encourage correct package

- CHANGELOG.md
- project/test/test_event.gd
- project/test/test_sdk.gd
- src/register_types.cpp
- src/sentry/disabled_event.h
- src/sentry/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/level.cpp
- src/sentry/level.h
- src/sentry/native/native_event.cpp
- src/sentry/native/native_event.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry/native/native_util.cpp
- src/sentry/native/native_util.h
- src/sentry_event.cpp
- src/sentry_event.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
This PR implements:
- `SentryEvent` objects, which can be used to create or modify an event, and a native implementation.
- `NativeEvent` class -- implementation used with `NativeSDK`
- Add `SentrySDK.capture_event(event)`, `SentrySDK.create_event()` methods.
- Unit tests for the `SentryEvent` class and SDK methods.
In future PRs, we can implement accessing tags, breadcrumbs, contexts, fingerprint, etc.
Dependency for: 
- #47 
- #46
> feat: Event objects

- CHANGELOG.md
- src/register_types.cpp
- src/sentry/godot_error_types.h
- src/sentry/native/native_sdk.cpp
- src/sentry/simple_bind.h
- src/sentry_logger.cpp
- src/sentry_options.cpp
- src/sentry_options.h
This PR improves `SentryOptions` and exposes it in the public API. This is needed for event hooks, in-code configuration support, integration tests and probably more.
Includes:
- Expose `SentryOptions` in the public API
- Add setters & bind properties
- New macros to streamline property binding in `ClassDB` (reduce boilerplate)
- Extract limits into its own public API class -- `SentryLoggerLimits`
- Refactor `SentryOptions` loading from project settings
Reviewer tip: it might be easier to look at changes commit-by-commit.
Resolves #55
Dependency for:
- #47
- #48
> feat: Improve & expose `SentryOptions` class

- .craft.yml
- scripts/post-release.ps1
Add a postRelease script to bump version for development right after release, and commit and push such changes to the repo. This script will be executed by `craft` right after release is made.
Expected results:
- `0.1.4` => `0.2.0-dev`
- `0.2.0-rc.0` => `0.2.0-rc.1`
WARNING: Running this script will push the respective changes to the tracked remote of the `main` branch!
> ci: Add post-release script

- CHANGELOG.md
- project/example_configuration.gd
- src/sentry/contexts.cpp
- src/sentry/environment.cpp
- src/sentry/environment.h
- src/sentry/native/native_sdk.cpp
- src/sentry_options.cpp
- src/sentry_options.h
This PR adds `SentryOptions.environment` property. Environment is auto-detected for user convenience, and it will be possible to assign it after #60 is merged.
Also, change auto-detected environment names to [prioritize development environments](https://develop.sentry.dev/application-architecture/dynamic-sampling/fidelity-and-biases/#prioritize-dev-environments).
Resolves #64
> feat: Add environment property to `SentryOptions`

- .github/workflows/build_gdextension.yml
- CHANGELOG.md
Fix #87
Looks like `symbols_visibility=visible` causes issues with other extensions.
> fix: Crash on macOS with GodotSteam

- scripts/bump-version.ps1
- scripts/post-release.ps1
Should fix https://github.com/getsentry/publish/issues/4986
The problem is with `oldVersion` parameter being mandatory while [receiving an empty string](https://github.com/getsentry/craft/blob/8dd907ecc67d9b399e1cf340031e3809f7a0108c/src/commands/publish.ts#L410).
> ci: Fix post-release script failure

- CHANGELOG.md
- src/sentry_sdk.cpp
Autofix crashpad handler executable bit permissions on Unix platforms if the user extracts the distribution archive without preserving such permissions. This fix is only applied in debug builds. I don't think we should be doing this in a release export.
> fix: Autofix crashpad handler executable bits

- CHANGELOG.md
- src/register_types.cpp
- src/sentry/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/native/native_sdk.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
Also, remove unnecessary `is_initialized()` method.
Resolves #81
> feat: Expose `SentrySDK.is_enabled()`

- CHANGELOG.md
- project/test/test_sentry_user.gd
- src/runtime_config.cpp
- src/runtime_config.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
- src/sentry_user.cpp
- src/sentry_user.h
Explicitly set `user.ip_address` to "{{auto}}" if `options.send_default_pii` is enabled and the dev didn't set user data explicitly (i.e. in a configuration script).
Additionally:
- Ensure the user is properly set even if `set_user()` is called before initialization.
- User data is no longer saved to disk. This is a **breaking change**.
- Another **breaking change** is `user.is_user_valid()` is replaced in favor of `user.is_empty()`.
Resolves #95
Related to https://github.com/getsentry/team-sdks/issues/118
> feat: Explicitly set `user.ip_address` to `{{auto}}`

- src/register_types.cpp
This PR fixes an issue with the error logger not starting. This issue was recently introduced in #82. I discovered it while working on the new unit tests.
#skip-changelog because this bug didn't get into release.
> fix: Error logger not starting

- CHANGELOG.md
- src/manifest.gdextension
- src/sentry/native/native_sdk.cpp
Fix issues with crashpad_handler not copied on export alongside the executable.
And fix expected handler path on macOS: it is located in Contents/Frameworks.
Addressing #107
> fix: Issues with exporting crashpad_handler dependency

- CHANGELOG.md
- project/test/suites/test_sentry_user.gd
- src/runtime_config.cpp
- src/sentry/contexts.cpp
- src/sentry_sdk.cpp
This PR fixes regression: user ID is no longer assigned to installation ID by default.
> fix: `user.id` not assigned to `installation_id` by default

- CHANGELOG.md
- project/project.godot
- src/sentry_options.cpp
This PR renames Sentry/Config to Sentry/Options, for consistency's sake. It's a **breaking change** (options will be reset in user projects).
> ref: Rename Sentry/Config category in Project Settings to Sentry/Options

- CHANGELOG.md
- src/sentry_logger.cpp
- src/sentry_logger.h
This PR fixes the following:
- Log file position not properly restored on macOS, and as a consequence, the logger is not working on Mac.
- Logger not showing debug output in Output pane.
> fix: Logger issues on macOS

- .github/workflows/unit_tests.yml
- project/test/isolated/test_limit_repeating_error_window.gd
Run tests in CI using macos-latest runner to detect issues related to Mac builds. In addition, fix flaky logger test.
> ci: Run unit tests on macos-latest

- CHANGELOG.md
- project/project.godot
Also, enable texture compression for Mac exports.
> fix: Demo output not updating in exported project

- CHANGELOG.md
- project/example_configuration.gd
- project/testing_configuration.gd
This PR fixes an issue with the exported demo project failing to initialize.
> fix: Demo project fails to initialize in exported environment

- CHANGELOG.md
- src/sentry/native/native_sdk.cpp
Previously, a screenshot was still taken and saved to a file if the option was disabled.
See also: 
- #148
> fix: Don't process screenshot when `attach_screenshot` option is disabled

- CHANGELOG.md
- doc_classes/SentryOptions.xml
See also #146.
Linked PR:
- https://github.com/getsentry/sentry-docs/pull/13089
> fix: Add missing documentation for `debug_verbosity` option

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- src/sentry/native/native_sdk.cpp
- src/sentry/util/screenshot.cpp
- src/sentry_logger.cpp
Note: Saving image from the root viewport is a slow operation: ~20 ms for JPG, 40 ms for PNG.
* ~~Don't take screenshots on non-crash events as it's too expensive.~~
* Use JPG format to speed up compression.
* Ensure that a screenshot is taken no more than once per frame drawn.
* Mention performance impact in the built-in documentation.
Addressing https://github.com/getsentry/sentry-godot/issues/110#issuecomment-2743714520
CI fails because of #147.
> ref: Optimize screenshot feature to reduce stutters

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- project/test/suites/test_options.gd
- src/sentry/native/native_sdk.cpp
- src/sentry_options.cpp
- src/sentry_options.h
This PR introduces `screenshot_level` option and `before_capture_screenshot` hook to provide fine-grained control over when screenshots are taken. 
- Add `screenshot_level` option to specify minimum event level threshold for screenshot capturing, defaulting to `FATAL`
- Add `before_capture_screenshot` hook for fine-grained control
- Fix potential feedback looping in event processing
Supersedes:
- #151
> feat: Screenshot level option & `before_capture_screenshot` hook

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- project/test/suites/test_options.gd
- src/sentry/util/print.h
- src/sentry_options.cpp
- src/sentry_options.h
Rename `debug_verbosity` => `diagnostic_level` to better align with established Sentry features.
Also, add a test for `diagnostic_level`.
> ref: Rename `debug_verbosity` => `diagnostic_level`

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- project/project.godot
- project/test/isolated/test_limit_events_per_frame.gd
- project/test/isolated/test_limit_repeating_error_window.gd
- project/test/isolated/test_limit_throttling.gd
- project/test/isolated/test_logger_disabled.gd
- project/test/isolated/test_logger_with_masks.gd
- project/test/isolated/test_logger_with_masks_empty.gd
- project/test/suites/test_options.gd
- src/register_types.cpp
- src/sentry_logger.cpp
- src/sentry_options.cpp
- src/sentry_options.h
This PR restructures options in the Project Settings:
- Mark options as basic and advanced to have a cleaner interface.
- Move error logger tunables into their own sub-page. This is a **BREAKING** change so make sure to reapply those error logger values if you're changing the defaults.
- Rename options: `error_logger_*` => `logger_*`.
> ref: Restructure options

- CHANGELOG.md
- doc_classes/SentrySDK.xml
- src/sentry/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
Seeing that it had a default value and seldom used, it shouldn't be a disruptive change.
Resolves #160
> ref: Remove `logger` argument from `SentrySDK.capture_message(...)`

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- project/main.gd
- project/project.godot
- project/test/suites/test_options.gd
- src/sentry/native/native_sdk.cpp
- src/sentry/view_hierarchy.cpp
- src/sentry/view_hierarchy.h
- src/sentry_options.cpp
- src/sentry_options.h
This PR implements automatic capturing of scene tree hierarchy data. In Sentry, this feature is more commonly known as View Hierarchy. It's an opt-in feature that can be enabled by setting the `attach_scene_tree` option to `true`.
Implements #113
Resolves #166
Waiting for the product changes:
- https://github.com/getsentry/sentry/issues/88788
Depends on:
- https://github.com/getsentry/sentry-native/pull/1191
Documentation PR:
- https://github.com/getsentry/sentry-docs/pull/13531
Remaining tasks:
> feat: View Hierarchy

- CHANGELOG.md
- doc_classes/SentryConfiguration.xml
- doc_classes/SentryEvent.xml
- doc_classes/SentryOptions.xml
- project/example_configuration.gd
- project/test/suites/test_event.gd
- project/test/suites/test_event_integrity.gd
- project/test/suites/test_options.gd
- src/sentry/disabled_event.h
- src/sentry/native/native_event.cpp
- src/sentry/native/native_event.h
- src/sentry/native/native_sdk.cpp
- src/sentry_event.cpp
- src/sentry_event.h
- src/sentry_options.cpp
- src/sentry_options.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
- Remove `on_crash` callback, since it is practically the same as `before_send`.
- Call `before_send` for crash events instead.
- Add `SentryEvent.is_crash()` method.
Before merge:
> ref: Remove `on_crash` hook in favor of `event.is_crash()`

- CHANGELOG.md
- SConstruct
- doc_classes/SentryUser.xml
- project/test/suites/test_event_integrity.gd
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry_sdk.cpp
- src/sentry_sdk.h
- src/sentry_user.cpp
- src/sentry_user.h
* Store last_uuid as atomic
* Synchronize access to SentryUser
* Add test for threaded event capture
* Add `SentryUser.duplicate()`
> ref: Improve thread safety

- src/sentry/disabled_event.h
- src/sentry/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/native/native_event.cpp
- src/sentry/native/native_event.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry_event.h
- src/sentry_logger.cpp
This is needed for both godot-4.5 branch and android.
#skip-changelog since it's a pure refactor
> ref: Implement Event.add_exception() to replace capture_error()

- CHANGELOG.md
- SConstruct
- src/editor/sentry_editor_export_plugin_unix.cpp
- src/editor/sentry_editor_export_plugin_unix.h
- src/editor/sentry_editor_plugin.cpp
- src/editor/sentry_editor_plugin.h
- src/register_types.cpp
Add editor export plugin to automatically set executable permissions for crashpad_handler binary on Unix platforms after project export. This prevents runtime failure to launch handler on Unix platforms.
- The problem manifests mainly on macOS and Linux, where crashpad_handler loses executable permissions on exporting Linux builds.
- The fix is not needed on Windows as in my tests exporting to a ZIP archive works just fine, preserving the necessary executable permissions.
- Plugin now autofixes permissions automatically on project export on Unix platforms.
- Exporting ZIP files for Linux also preserves permissions (tested on macOS).
- The fix is also applied to APP bundles, and zipped APP bundles, just in case. It may not be necessary, but we have a previous report that suggests maybe …
> fix: Ensure crashpad_handler has executable permissions on Unix exports

- src/sentry/contexts.cpp
- src/sentry_sdk.cpp
* Don't add device and app contexts on Android since those are handled by the Android SDK.
* Fix device memory info can contain invalid values on some platforms.
#skip-changelog since we didn't release with this issue
> fix: Don't add device and app contexts on Android

- scripts/run-isolated-tests.ps1
Starting with Godot 4.4, additional files are created for each script, and it happens that our routine executes for those files as well.
> ci: Fix isolated tests routine executed for .uid files

- CONTRIBUTING.md
Add instruction on how to build supporting library, and such.
> docs: Add Android instructions to CONTRIBUTING

- CHANGELOG.md
Sync `godotcpp` submodule with `Godot 4.5-beta3`
- Note: We don't automatically bump this dependency because it needs to stay pinned to the minimum version supported.
> chore: Bump godot-cpp to sync with Godot 4.5-beta3

- CHANGELOG.md
- src/sentry_sdk.cpp
- Due to a bug, currently, it's not possible to disable SDK programmatically. 
- Fixes #249
> fix: Check options.enabled during SDK initialization

- CHANGELOG.md
- src/sentry_sdk.cpp
- Fix null pointer dereference in SentrySDK::get_user
> fix: Fix crashing when SDK is disabled via options

- CHANGELOG.md
- src/sentry/sentry_sdk.cpp
> fix: Allow configuration script to run even if SDK is initially disabled in project settings

- CHANGELOG.md
- src/sentry/contexts.cpp
- src/sentry/sentry_sdk.cpp
Remove redundant context initialization that was resulting in errors at runtime in early initialization path (no configuration script used). For information, we initialize context [here](https://github.com/getsentry/sentry-godot/blob/main/src/sentry/sentry_sdk.cpp#L385) and [here](https://github.com/getsentry/sentry-godot/blob/main/src/sentry/sentry_sdk.cpp#L310), depending if configuration script is used (early vs delayed init).
- Also add additional null checks.
- Fixes #263
> fix: Context-related errors generated at runtime with early intialization

- CHANGELOG.md
- src/sentry/sentry_logger.cpp
- src/sentry/sentry_logger.h
This PR fixes a runtime error with Logger not being able to connect to a signal on the main loop during the early initialization path, because the main loop is not yet available.
Also, disconnect from the mentioned signal on free.
> fix: Logger connecting to signal runtime error with early initialization

- CHANGELOG.md
- src/sentry/sentry_logger.cpp
This PR adds prevention mechanism for infinite feedback loops in the logger which may lead to crashes.
> fix: Prevent feedback loops in SentryLogger

- CHANGELOG.md
- src/sentry/sentry_options.cpp
- src/sentry/sentry_options.h
Fix `release` option not honored if set to a custom value in the project settings, and fix parsing of `app_name`/`app_version` replacement tokens if set via a configuration script.
> fix: `release` option value ignored

- .github/actions/prepare-testing/action.yml
- CHANGELOG.md
Bump minimum compatibility to `4.5-beta4`
> chore: Bump Godot compatibility to `4.5-beta4`

- modules/sentry-cocoa.SConscript
- src/sentry/cocoa/cocoa_event.h
Enable ARC (automatic reference counting) in Objective C/C++ files when compiling with Cocoa SDK.
So, it turns out that ARC wasn’t turned on in the builds, which caused some memory leaks and other problems. Since we don’t manually release objects, this was a bit of a surprise.
I used this code to test ARC:
```cpp
void test_arc_behavior() {
print_line("--- STARTING ARC TEST");
@autoreleasepool {
objc::SentryEvent *event = [[objc::SentryEvent alloc] init];
print_line("--- NEW EVENT CREATED");
__weak objc::SentryEvent *weak_ref = event;
print_line("--- WEAK REF SET - IS NIL: ", (weak_ref == nil));
// Clear the strong reference
event = nil;
print_line("--- AFTER CLEARING STRONG REF - WEAK IS NIL: ", (weak_ref == nil));
}
}
```
Before this PR (compilation error):
``` …
```
> fix: Enable ARC when compiling with Cocoa SDK

- CHANGELOG.md
- SConstruct
- This allows creating iOS XCFramework from previously built binaries without triggering a build process.
- We need this for CI to create the final framework in the package.
- The framework creation can be triggered by running: 
- `scons platform=ios target=template_release ios_framework`
- `scons platform=ios target=editor ios_framework`
- Extracted from #291
> build: Add iOS framework as optional build target

- .github/workflows/build_gdextension.yml
Make usable iOS builds in CI. This PR adds a job to combine GDExtension iOS artifacts into XCFramework.
> ci: Build iOS artifacts

- CHANGELOG.md
- doc_classes/SentryOptions.xml
- src/sentry/sentry_logger.cpp
- src/sentry/sentry_options.cpp
- src/sentry/sentry_options.h
This PR adds option `logger/messages_as_breadcrumbs` which is enabled by default. This allows disabling messages as breadcrumbs by a simple toggle. Since some projects `print()` heavily into console, this option should be quite useful.
- Resolves #293
> feat: Add option to disable logging messages as breadcrumbs

- .github/actions/prepare-testing/action.yml
- .github/workflows/build_gdextension.yml
- CHANGELOG.md
BREAKING: Compatible Godot version is `4.5-beta5`.
> chore: Bump Godot compatibility to 4.5-beta5

- CHANGELOG.md
- src/sentry/cocoa/cocoa_event.mm
- src/sentry/cocoa/cocoa_util.h
- src/sentry/cocoa/cocoa_util.mm
This PR adds support for scripting source context and local variables on iOS and macOS.
- Note: Builds will fail to compile without Cocoa SDK changes.
- Waiting for changes in Cocoa SDK https://github.com/getsentry/sentry-cocoa/pull/5853
Before this PR: 
After this PR:
> feat: Add support for script context and variables on Apple platforms

- CHANGELOG.md
- src/register_types.cpp
- src/sentry/android/android_sdk.cpp
- src/sentry/android/android_sdk.h
- src/sentry/cocoa/cocoa_sdk.h
- src/sentry/cocoa/cocoa_sdk.mm
- src/sentry/disabled/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry/sentry_sdk.cpp
- src/sentry/sentry_sdk.h
This PR cleans up and restructures initialization flow in preparation for lifecycle methods, extracted from #321.
- Clean up module initialization and class registration.
- Add SentrySDK create_singleton()/destroy_singleton() functions for cleaner code.
- Separate SentrySDK construction from SDK auto initialization.
- Ensure InternalSDK interface is created early (in constructor).
- Move startup and initialization logic from constructor into `prepare_and_auto_initialize()` method.
- Rename InternalSDK initialize() => init() to better align with Sentry terminology.
- Better function names.
These changes make it easier to follow the initialization flow and reduce the risk of errors.
> ref: Improve initialization flow

- CHANGELOG.md
- android_lib/build.gradle.kts
- android_lib/src/main/java/io/sentry/godotplugin/SentryAndroidGodotPlugin.kt
- android_lib/src/main/java/io/sentry/godotplugin/UtilityFunctions.kt
- android_lib/src/test/java/io/sentry/godotplugin/UtilityFunctionsTest.kt
This PR sets minimum Android SDK compatibility to 24 as in the upcoming Godot 4.5, and replaces API 26-only calls to ensure such compatibility.
> fix: Ensure compatibility with minSdk 24 on Android

- CHANGELOG.md
- src/register_types.cpp
- src/sentry/android/android_event.cpp
- src/sentry/android/android_event.h
- src/sentry/android/android_sdk.cpp
- src/sentry/android/android_sdk.h
- src/sentry/android/android_string_names.cpp
- src/sentry/android/android_string_names.h
- src/sentry/native/native_event.cpp
- src/sentry/native/native_event.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry/sentry_sdk.cpp
Move Native and Android classes into their own namespace, similar to Cocoa internals.
> ref: Move native and android code into respective namespaces

- CHANGELOG.md
- project/test/suites/test_event.gd
- project/test/suites/test_sdk.gd
- src/sentry/native/native_event.cpp
This PR fixes issues with retaining UTF-8 encoding in native SentryEvent implementation, discovered while working on tests in #326. The problem is that getters should be using String::utf8() where we reasonably expect UTF-8. Extracted from #326.
- Fixes #336
- Partially implements #337, more are coming in #326
> fix: UTF-8 retention problems with native SentryEvent properties

- .github/actions/prepare-testing/action.yml
- .github/workflows/unit_tests.yml
- .gitmodules
- project/project_main_loop.gd
- project/test/suites/test_attachment.gd
- project/test/suites/test_breadcrumb.gd
- project/test/suites/test_event.gd
- project/test/suites/test_event_integrity.gd
- project/test/suites/test_options.gd
- project/test/suites/test_sdk.gd
- project/test/suites/test_sentry_user.gd
- project/test/suites/test_timestamp.gd
- project/test/util/sentry_test_suite.gd
- project/test/util/sentry_test_suite.gd.uid
This PR adds tools to support testing in GDScript:
- Add [JSONAssert](https://github.com/getsentry/gdunit-json-assert) submodule – a tool that lets us query and assert on JSON content
- The [tool](https://github.com/getsentry/gdunit-json-assert/blob/main/JSONAssertImpl.gd) was extracted into its own repository.
- It comes with a [test suite](https://github.com/getsentry/gdunit-json-assert/blob/main/test_json_assert.gd) that is added to our CI runs in this PR.
- See examples of usage in #326 (which this PR was extracted from).
- Add `SentryTestSuite` – supporting base class for our test suites that initializes the SDK for testing and integrates JSONAssert tool
- Update old tests to use the new `SentryTestSuite` as a base class
- This is important because the regular test run needs to be …
> test: Add JSONAssert and SentryTestSuite

- CHANGELOG.md
- src/sentry/sentry_logger.cpp
Strip ASCII escape sequences and control characters from logger breadcrumbs. We're capturing Godot logger messages as breadcrumbs, and sometimes those messages contain unprintable control characters intended for terminal. Godot doesn't filter those sequences, hence this PR. 
- This affects any colorized output such as with `print_rich()`.
- Cocoa is particularly noisy, when such characters are added as breadcrumbs, making understanding unit test results very hard, as it produces a ton of errors.
- Closes #351
> feat: Strip invisible characters from logger breadcrumbs

- CHANGELOG.md
- doc_classes/SentryLoggerLimits.xml
- project/test/isolated/test_limit_throttling_disabled.gd
- project/test/isolated/test_limit_throttling_disabled.gd.uid
- src/sentry/sentry_logger.cpp
Fix setting `throttle_window_ms` to 0 should disable throttling, and clarify this in the class docs.
- Closes #270
> fix: Setting `throttle_window_ms` to 0 should disable it

- README.md
Depends on:
- https://github.com/getsentry/sentry-docs/pull/15019
> chore: Add link to migration guide in README

- CHANGELOG.md
- src/sentry/android/android_sdk.cpp
- src/sentry/android/android_sdk.h
- src/sentry/cocoa/cocoa_sdk.h
- src/sentry/cocoa/cocoa_sdk.mm
- src/sentry/disabled/disabled_sdk.h
- src/sentry/internal_sdk.h
- src/sentry/native/native_sdk.cpp
- src/sentry/native/native_sdk.h
- src/sentry/sentry_sdk.cpp
This PR fixes `The SDK is disabled, so setUser doesn't work`  error on Apple platforms. Initial user is now set in the initialScope on Apple, and after init() on other platforms that don't support initial scope. This also adds null user handling directly to internal SDK implementations to prevent crashing.
- Resolves #388
> fix: Failing to set initial user on Apple platforms

- CHANGELOG.md
- SConstruct
- site_scons/site_tools/plist.py
Generate Info.plist for GDExtension library on macOS. This fixes the warning during Godot export, and generic Info.plist added.
- Depends on #399 
- Resolves #112
> build: Generate Info.plist for macOS

- CHANGELOG.md
- SConstruct
- site_scons/site_tools/separate_debug_symbols.py
Introduce support for separating debug symbols of Android targets using the `separate_debug_symbols` option.
Additionally, refactor the separation process to function as a post-action rather than a builder, addressing an issue where subsequent runs produced empty symbol files.
> build: Support separating debug symbols of Android targets
